(********************************************************************
 * COPYRIGHT -- B&R Industrial Automation GmbH
 ********************************************************************
 * Program: myProg
 * File: myProg.st
 * Author: hilchenbachc
 * Created: November 22, 2022
 ********************************************************************
 * Implementation of program myProg
 ********************************************************************)

PROGRAM _INIT
	myUSINT;
	myUINT;
	mySTRING;
	myWSTRING;
	myTIME;
	myTOD;
	myDT;
	myDINT;
	myINTArray;
	mySTRINGArray;
	myWSTRINGArray;
	myUDINT;
	myDATE;
	myLREAL;
	myREAL;
	myINT;
	mySINT;
	myBOOL;
	myREALArray;
	myEnumeration;
	myDerivedDataType;
	mySimpleStruct;
	myStructArray;
	myComplexStruct;
END_PROGRAM

PROGRAM _CYCLIC

END_PROGRAM
