(********************************************************************
 * COPYRIGHT -- Bernecker + Rainer
 ********************************************************************
 * Program: visAlarm
 * File: visAlarmInit.st
 * Author: B&R
 * Created: November 22, 2007
 ********************************************************************
 * Implementation of program visAlarm
 ********************************************************************)

PROGRAM _INIT


(* TODO : Add your code here *)


END_PROGRAM

